In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("main.csv", sep=';')

In [3]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d %H:%M:%S%z', utc=True)
df.set_index('Date', inplace=True)
df.index = df.index.tz_convert('Europe/Amsterdam')

In [4]:
df['Final_Price'] = np.where(~df['Short_Price'].isna(), df['Short_Price'],
                    np.where(~df['Long_Price'].isna(), df['Long_Price'], df['Mid_Price']))
df.drop(columns=['Long_Price', 'Short_Price'], inplace=True)

In [5]:
df.drop(columns=['BE to NL (from Belgium)', 'DE to NL (from Germany)',
       'DK to NL (from Denmark)', 'NO to NL (from Norway)',
       'NL to BE (to Belgium)', 'NL to DE (to Germany)',
       'NL to DK (to Denmark)', 'NL to NO (to Norway)','Belgium Intraday',
       'Denmark Intraday', 'Germany Intraday', 'Great Britain Intraday',
       'Norway Intraday'], inplace=True)

In [6]:
df['Dispatch'] = df['Upward_Dispatch'] - df['Downward_Dispatch']
df['IGCC_Dispatch'] = df['IGCCCONTRIBUTION_UP'] - df['IGCCCONTRIBUTION_DOWN']

In [7]:
df.drop(columns=['Upward_Dispatch','Downward_Dispatch', 'IGCCCONTRIBUTION_UP', 'IGCCCONTRIBUTION_DOWN'], inplace=True)

In [8]:
for i in df.columns:
    print(i,sum(df[i].isna()))

Reserve_Upward_Dispatch 187
Reserve_Downward_Dispatch 187
Emergency_Power 0
Mid_Price 187
minmax 0
min600 0
min300 0
min100 0
minmin 0
posmin 0
pos100 0
pos300 0
pos600 0
posmax 0
SOLAR FORECAST (TENNET) 0
SOLAR FORECAST (ENAPPSYS) 324000
SOLAR OUTTURN 0
SOLAR DA FORECAST (TENNET) 0
DAY AHEAD FORECAST (ENAPPSYS) 0
INFERRED INSTALLED CAPACITY (ENAPPSYS)_x 0
SOLAR ID FORECAST (TENNET) 0
SOLAR FORECAST UNADJUSTED (ENAPPSYS) 0
WIND ONSHORE OUTTURN 0
WIND OFFSHORE OUTTURN 0
OFFSHORE WIND FORECAST (ENAPPSYS) 326940
ONSHORE WIND FORECAST (ENAPPSYS) 324000
WIND FORECAST (ENAPPSYS) 329820
WIND FORECAST (TENNET) 0
WIND DA FORECAST (TENNET) 0
WIND ID FORECAST (TENNET) 0
FORECAST D-1 (ENAPPSYS) 0
WIND FORECAST UNADJUSTED (ENAPPSYS) 0
INFERRED INSTALLED CAPACITY (ENAPPSYS)_y 0
OFFSHORE WIND GENERATION (ENTSOE) 0
DAY AHEAD NTC (to Netherlands) 0
DAY AHEAD NTC (from Netherlands) 0
Intraday Traded 0
DA Scheduled Flow 0
Scheduled Flow 0
BELGIUM (BE) 0
DENMARK (DK) 0
GERMANY (DE) 0
GREAT BRITAIN (GB) 0
GREAT BRITAIN (GB - EPEX) 0
GREAT BRITAIN (GB - NORDPOOL) 0
NETHERLANDS (NL) 0
NORWAY (NO) 0
Final_Price 187
Dispatch 187
IGCC_Dispatch 187

In [9]:
df['MinuteOfDay'] = df.index.hour * 60 + df.index.minute
df['HourOfDay'] = df.index.hour
df['Imbalance_Price -2H'] = df['Final_Price'].shift(periods=-2, freq='1H')
df['IGCC_Dispatch -2H'] = df['IGCC_Dispatch'].shift(periods=-2, freq='1H')
df['Dispatch -2H'] = df['Dispatch'].shift(periods=-2, freq='1H')
df['Imbalance_Price -5m'] = df['Final_Price'].shift(periods=-5, freq='1T')
df['IGCC_Dispatch -5m'] = df['IGCC_Dispatch'].shift(periods=-5, freq='1T')
df['Dispatch -5m'] = df['Dispatch'].shift(periods=-2, freq='5T')
df['WIND OUTTURN'] = df['WIND ONSHORE OUTTURN'] + df['WIND OFFSHORE OUTTURN']
df['NETTO SOLAR'] = df['SOLAR OUTTURN'] - df['DAY AHEAD FORECAST (ENAPPSYS)']
df['NETTO WIND'] = df['FORECAST D-1 (ENAPPSYS)'] - df['WIND OUTTURN']
df['Final_Price +2H'] = df['Final_Price'].shift(periods=2, freq='1H')

In [10]:
df[['Final_Price', 'Imbalance_Price -5m']].tail(20)

                           Final_Price  Imbalance_Price -5m
Date
2022-12-31 23:40:00+01:00       -15.18               -24.40
2022-12-31 23:41:00+01:00       -15.18               -15.18
2022-12-31 23:42:00+01:00       -24.40               -15.18
2022-12-31 23:43:00+01:00       -24.40               -15.18
2022-12-31 23:44:00+01:00       -24.40               -15.18
2022-12-31 23:45:00+01:00       -24.40               -15.18
2022-12-31 23:46:00+01:00       -15.18               -10.58
2022-12-31 23:47:00+01:00       -15.18               -10.00
2022-12-31 23:48:00+01:00       -15.18                10.00
2022-12-31 23:49:00+01:00       -15.18                10.00
2022-12-31 23:50:00+01:00       -15.18                10.00
2022-12-31 23:51:00+01:00       -10.58                10.00
2022-12-31 23:52:00+01:00       -10.00                10.00
2022-12-31 23:53:00+01:00        10.00               -10.58
2022-12-31 23:54:00+01:00        10.00               -24.40
2022-12-31 23:55:00+01:00        10.00                  NaN
2022-12-31 23:56:00+01:00        10.00                  NaN
2022-12-31 23:57:00+01:00        10.00                  NaN
2022-12-31 23:58:00+01:00       -10.58                  NaN
2022-12-31 23:59:00+01:00       -24.40                  NaN

In [11]:
df = df["2021-12-31 23:00:00+01:00":"2022-12-31 21:59:00+01:00"]

In [12]:
df.head()

,Reserve_Upward_Dispatch,Reserve_Downward_Dispatch,Emergency_Power,Mid_Price,minmax,min600,min300,min100,minmin,posmin,...,Imbalance_Price -2H,IGCC_Dispatch -2H,Dispatch -2H,Imbalance_Price -5m,IGCC_Dispatch -5m,Dispatch -5m,WIND OUTTURN,NETTO SOLAR,NETTO WIND,Final_Price +2H
Date,,,,,,,,,,,,,,,,,,,,,
2021-12-31 23:00:00+01:00,0.0,0.0,0,136.18,-71.8,-71.8,-71.8,-20.58,132.37,139.99,...,151.18,-554.0,-190.0,177.85,0.0,118.0,4837.0,0.0,-1381.0,-8.86
2021-12-31 23:01:00+01:00,0.0,0.0,0,136.18,-71.8,-71.8,-71.8,-20.58,132.37,139.99,...,112.66,-550.0,-179.0,180.85,0.0,114.0,4830.8,0.0,-1374.8,-16.36
2021-12-31 23:02:00+01:00,0.0,0.0,0,136.18,-71.8,-71.8,-71.8,-20.58,132.37,139.99,...,112.66,-550.0,-165.0,180.85,0.0,109.0,4824.6,0.0,-1368.6,-33.91
2021-12-31 23:03:00+01:00,0.0,0.0,0,136.18,-71.8,-71.8,-71.8,-20.58,132.37,139.99,...,112.66,-550.0,-151.0,180.85,0.0,98.0,4818.4,0.0,-1362.4,-80.31
2021-12-31 23:04:00+01:00,0.0,0.0,0,136.18,-71.8,-71.8,-71.8,-20.58,132.37,139.99,...,112.66,-550.0,-144.0,180.85,0.0,89.0,4812.2,0.0,-1356.2,-85.10

In [13]:
for i in df.columns:
    print(i,sum(df[i].isna()))

Reserve_Upward_Dispatch 187
Reserve_Downward_Dispatch 187
Emergency_Power 0
Mid_Price 187
minmax 0
min600 0
min300 0
min100 0
minmin 0
posmin 0
pos100 0
pos300 0
pos600 0
posmax 0
SOLAR FORECAST (TENNET) 0
SOLAR FORECAST (ENAPPSYS) 59100
SOLAR OUTTURN 0
SOLAR DA FORECAST (TENNET) 0
DAY AHEAD FORECAST (ENAPPSYS) 0
INFERRED INSTALLED CAPACITY (ENAPPSYS)_x 0
SOLAR ID FORECAST (TENNET) 0
SOLAR FORECAST UNADJUSTED (ENAPPSYS) 0
WIND ONSHORE OUTTURN 0
WIND OFFSHORE OUTTURN 0
OFFSHORE WIND FORECAST (ENAPPSYS) 62040
ONSHORE WIND FORECAST (ENAPPSYS) 59100
WIND FORECAST (ENAPPSYS) 64920
WIND FORECAST (TENNET) 0
WIND DA FORECAST (TENNET) 0
WIND ID FORECAST (TENNET) 0
FORECAST D-1 (ENAPPSYS) 0
WIND FORECAST UNADJUSTED (ENAPPSYS) 0
INFERRED INSTALLED CAPACITY (ENAPPSYS)_y 0
OFFSHORE WIND GENERATION (ENTSOE) 0
DAY AHEAD NTC (to Netherlands) 0
DAY AHEAD NTC (from Netherlands) 0
Intraday Traded 0
DA Scheduled Flow 0
Scheduled Flow 0
BELGIUM (BE) 0
DENMARK (DK) 0
GERMANY (DE) 0
GREAT BRITAIN (GB) 0
GREAT BRITAIN (GB - EPEX) 0
GREAT BRITAIN (GB - NORDPOOL) 0
NETHERLANDS (NL) 0
NORWAY (NO) 0
Final_Price 187
Dispatch 187
IGCC_Dispatch 187
MinuteOfDay 0
HourOfDay 0
Imbalance_Price -2H 187
IGCC_Dispatch -2H 187
Dispatch -2H 187
Imbalance_Price -5m 187
IGCC_Dispatch -5m 187
Dispatch -5m 187
WIND OUTTURN 0
NETTO SOLAR 0
NETTO WIND 0
Final_Price +2H 187

In [14]:
from sklearn.impute import KNNImputer
df = df.loc[:, [
                'DAY AHEAD FORECAST (ENAPPSYS)',
                'SOLAR FORECAST UNADJUSTED (ENAPPSYS)',
                'WIND FORECAST UNADJUSTED (ENAPPSYS)',
                'FORECAST D-1 (ENAPPSYS)',
                'NETTO SOLAR',
                'NETTO WIND',
                'INFERRED INSTALLED CAPACITY (ENAPPSYS)_x',
                'SOLAR OUTTURN',
                'WIND OUTTURN',
                'INFERRED INSTALLED CAPACITY (ENAPPSYS)_y',
                'DA Scheduled Flow',
                'Scheduled Flow',
                'Final_Price',
                'Final_Price +2H', 
                'Dispatch', 
                'IGCC_Dispatch',
                'Dispatch -2H', 
                'HourOfDay',
                'MinuteOfDay',
                'IGCC_Dispatch -2H',
                'Imbalance_Price -2H',
                'Dispatch -5m',
                'IGCC_Dispatch -5m',
                'Imbalance_Price -5m',
                'minmax',
                'min600',
                'min300',
                'min100',
                'minmin',
                'posmin',
                'pos100',
                'pos300',
                'pos600',
                'posmax',
                'NETHERLANDS (NL)'
                ]]

original_index = df.index

imputer = KNNImputer(n_neighbors=5)
df_imputed = imputer.fit_transform(df)

df = pd.DataFrame(data=df_imputed, columns=df.columns, index=original_index)

In [15]:
df.columns

Index(['DAY AHEAD FORECAST (ENAPPSYS)', 'SOLAR FORECAST UNADJUSTED (ENAPPSYS)',
       'WIND FORECAST UNADJUSTED (ENAPPSYS)', 'FORECAST D-1 (ENAPPSYS)',
       'NETTO SOLAR', 'NETTO WIND', 'INFERRED INSTALLED CAPACITY (ENAPPSYS)_x',
       'SOLAR OUTTURN', 'WIND OUTTURN',
       'INFERRED INSTALLED CAPACITY (ENAPPSYS)_y', 'DA Scheduled Flow',
       'Scheduled Flow', 'Final_Price', 'Final_Price +2H', 'Dispatch',
       'IGCC_Dispatch', 'Dispatch -2H', 'HourOfDay', 'MinuteOfDay',
       'IGCC_Dispatch -2H', 'Imbalance_Price -2H', 'Dispatch -5m',
       'IGCC_Dispatch -5m', 'Imbalance_Price -5m', 'minmax', 'min600',
       'min300', 'min100', 'minmin', 'posmin', 'pos100', 'pos300', 'pos600',
       'posmax', 'NETHERLANDS (NL)'],
      dtype='object')

In [16]:
df.to_csv('preprocessed_data.csv', sep=';', index=True)